ballet_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('courses/', include('courses.urls')),
    path('jobs/', include('jobs.urls')),
    path('new-mail/', include('mail.urls')),
    path('venues/', include('venues.urls')),
    path('blogs/', include('blog.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [

    path('', BlogListingsView.as_view(), name='blog-listing'),
    path('detail/<int:pk>/', BlogListingDetail.as_view(), name='blog-detail'),
    path('category-detail/<int:pk>/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('create/', CreateBlogView.as_view(), name='create-blog')

]

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [
    path('listings/', ListingView.as_view(), name='jobs'),
    path('create-listing/', CreateListingView.as_view(), name='create-listing'),
    path('detail/<slug:slug>/<int:pk>/', SingleListingView.as_view(), name='single-listing'),
    path('update-listing/<slug:slug>/<int:pk>/', UpdateListingView.as_view(), name='update-listing'),
    path('delete/listing/<slug:slug>/<int:pk>/', DeleteListingView.as_view(), name='delete-listing'),
    path('delete/posting/<slug:slug>/<int:pk>/', DeletePostingView.as_view(), name='delete-posting'),
    path('category-detail/listings/<slug:slug>/<int:pk>/', CategoryListingsView.as_view(), name='category-listings'),
    path('category-detail/postings/<slug:slug>/<int:pk>/', CategoryPostingsView.as_view(), name='category-postings'),
    path('location-detail/postings/<slug:location>/', LocationPostingsView.as_view(), name='location-postings'),
    path('location-detail/listings/<slug:location>/', LocationListingsView.as_view(), name='location-listings'),
    path('search/listings/', search, name='search-listings'),
    path('search/postings/', searchPosting, name='search-postings'),
    path('postings/', PostingView.as_view(), name='postings'),
    path('create-posting', CreatePostingView.as_view(), name='create-posting'),
    path('post-detail/<slug:slug>/<int:pk>/', SinglePostingView.as_view(), name='single-posting'),
    path('update-posting/<slug:slug>/<int:pk>/', UpdatePostingView.as_view(), name='update-posting'),


]

mail/urls.py
from django.urls import path
from .views import *

app_name = 'mail'

urlpatterns = [
    path('inbox/', inbox, name='inbox'),
    path('inbox-new/', inbox_2, name='inbox'),
    path('outbox/', outbox, name='outbox'),
    path('create-communication/<int:pk>/', CreateCommunication.as_view(), name='create-communication'),
    path('create-communication-job/<int:pk>/', CreateCommunicationJob.as_view(), name='create-communication-job'),
    path('create-communication-venue/<int:pk>/', CreateCommunicationVenue.as_view(), name='create-communication-venue'),
    path('create-course-communication/<int:pk>/<int:course_id>/', CreateCourseCommunication.as_view(), name='create-course-communication'),
    path('create-talent-communication/<int:pk>/', CreateTalentCommunication.as_view(), name='create-talent-communication'),

    path('communication/<int:pk>/', communication_detail, name='communication'),
    path('delete-conversation/<int:pk>/', hide_conversation, name='delete-conversation'),
    # path('delete-conversation/<int:pk>/', HideConversationView.as_view(), name='delete-conversation'),



]

pages/urls.py
from django.urls import path
from .views import *

app_name ='pages'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('talent/', TalentListView.as_view(), name='talent'),
    path('talent/<int:pk>/<slug:slug>', TalentDetailView.as_view(), name='talent-detail'),
    path('profile-info/<int:pk>/<slug:first_name>/', ProfileInfoView.as_view(), name='profile-info'),
    path('search/talent/', searchTalent, name='search-talent'),



]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('update/<int:pk>', UserUpdateView.as_view(), name='update-profile'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('create_dancers_profile/', CreateDancerProfileView.as_view(), name='create-dancers-profile'),
    path('delete-dancers-profile/<int:pk>/', DeleteDancersProfile.as_view(), name='delete-dancers-profile'),
    path('create_company_profile/', CreateCompanyProfileView.as_view(), name='create-company-profile'),
    path('delete-company-profile/<int:pk>/', DeleteCompanyProfile.as_view(), name='delete-company-profile'),
    path('delete-photo/<int:pk>/', delete_dancer_photo, name='delete-dancers-photo'),
    path('activate/<uidb64>/<token>', VerificationView.as_view(), name='activate')


]

templates/partials/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
          {% else %}
            {{ message.tags|title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}



{##}
{#{% if messages %}#}
{#        {% for message in messages %}#}
{#            <div class="text-center alert alert-{{ message.tags }}">#}
{#                {{ message|safe }}#}
{#            </div>#}
{#        {% endfor %}#}
{#    {% endif %}#}

templates/partials/_footer.html
		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
              <h2>Dance Made Simple !!</h2>
{#              <div class="row d-flex justify-content-center mt-4 mb-4">#}
{#                <div class="col-md-8">#}
{#                  <form action="#" class="subscribe-form">#}
{#                    <div class="form-group d-flex">#}
{#                      <input type="text" class="form-control" placeholder="Enter email address">#}
{#                      <input type="submit" value="Subscribe" class="submit px-3">#}
{#                    </div>#}
{#                  </form>#}
{#                </div>#}
{#              </div>#}
            </div>
          </div>
        </div>
      </div>
    </section>

    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-2">
        	<div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About</h2>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Classes</h2>
            </div>
          </div>
            <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Jobs</h2>
            </div>
          </div>
            <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Talent</h2>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Venues</h2>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+077777777</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@balletdanceuk.co.uk</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved </p>
          </div>
        </div>
      </div>
    </footer>

templates/partials/_head.html
{% load static %}

  <head>
    <title>JobPortal - BalletDanceuk</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">

    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">


    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/my-style.css" %}">
    <link rel="stylesheet" href="{% static "css/lightbox.min.css" %}">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
    crossorigin="anonymous">
  </head>

templates/partials/_nav.html
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'pages:home' %}">BalletUK</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li
              {% if ' ' in request.path %}
                          class="nav-item active"
                      {% else %}
                          class="nav-item"
                      {% endif %}><a href="{% url 'pages:home' %}" class="nav-link">Home</a></li>
	          <li
                  {% if 'courses' in request.path %}
                      class="nav-item active"
                  {% else %}
                      class="nav-item"
                  {% endif %}
                      ><a href="{% url 'courses:courses' %}" class="nav-link">Classes</a></li>
                <li class="btn-group" style="margin-top: 10px">
                    <button type="button" class="btn btn-sadie-outline  dropdown-toggle nav-link-2" style="height: 35px" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Jobs
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'jobs:jobs' %}">Jobs</a>
                        <a class="dropdown-item" href="{% url 'jobs:postings' %}">Specific Date Jobs</a>
                      </div>
                </li>
                <li
                    {% if 'talent' in request.path %}
                      class="nav-item active"
                    {% else %}
                      class="nav-item"
                    {% endif %}
              ><a href="{% url 'pages:talent' %}" class="nav-link">Talent</a></li>
	          <li
                      {% if 'venues' in request.path %}
                          class="nav-item active"
                      {% else %}
                          class="nav-item"
                      {% endif %}><a href="{% url 'venues:venues' %}" class="nav-link">Venues</a></li>
	          <li
                      {% if 'blog' in request.path %}
                          class="nav-item active"
                      {% else %}
                          class="nav-item"
                      {% endif %}
              ><a href="{% url 'blog:blog-listing' %}" class="nav-link">Blog</a></li>
                {% if  user.is_authenticated %}<!-- Example single danger button -->
                        <div class="btn-group" style="margin-top: 10px">
                          <button type="button" class="btn btn-danger dropdown-toggle" style="height: 35px" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              {{ user.first_name |title }}
                          </button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'mail:inbox' %}">Messages</a>
                            <a class="dropdown-item" href="{% url 'jobs:create-listing' %}">Add Job</a>
                            <a class="dropdown-item" href="{% url 'jobs:create-posting' %}">Add Specific Date Job</a>
                            <a class="dropdown-item" href="{% url 'courses:create-course' %}">Add Class</a>
                            <a class="dropdown-item" href="{% url 'venues:add-venue' %}">Add Venue</a>
                            <a class="dropdown-item" href="{% url 'blog:create-blog'  %}">Create Blog </a>
                            <a class="dropdown-item" href="{% url 'users:profile' user.pk %}">Profile | Update</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                          </div>
                        </div>
                {% else %}
                    <li class="nav-item cta mr-md-2"><a href="{% url 'users:login' %}" class="nav-link">Login</a></li>
                    <li class="nav-item cta cta-colored"><a href="{% url 'users:register' %}" class="nav-link">Register</a></li>

                {% endif %}

	        </ul>
	      </div>
	    </div>
	  </nav>

templates/partials/_static.html
{% load static %}

<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery.easing.1.3.js" %}"></script>
<script src="{% static "js/jquery.waypoints.min.js" %}"></script>
<script src="{% static "js/jquery.stellar.min.js" %}"></script>
<script src="{% static "js/owl.carousel.min.js" %}"></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/aos.js" %}"></script>
<script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
<script src="{% static "js/bootstrap-datepicker.js" %}"></script>
<script src="{% static "js/jquery.timepicker.min.js" %}"></script>
<script src="{% static "js/scrollax.min.js" %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static "js/google-map.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
<script src="{% static "js/lightbox-plus-jquery.min.js" %}"></script>