ballet_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('courses/', include('courses.urls')),
    path('jobs/', include('jobs.urls')),
    path('new-mail/', include('mail.urls')),
    path('venues/', include('venues.urls')),
    path('blogs/', include('blog.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [

    path('', BlogListingsView.as_view(), name='blog-listing'),
    path('detail/<int:pk>/', BlogListingDetail.as_view(), name='blog-detail'),
    path('category-detail/<int:pk>/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('create/', CreateBlogView.as_view(), name='create-blog')

]

mail/urls.py
from django.urls import path
from .views import *

app_name = 'mail'

urlpatterns = [
    path('inbox/', inbox, name='inbox'),
    path('inbox-new/', inbox_2, name='inbox'),
    path('outbox/', outbox, name='outbox'),
    path('create-communication/<int:pk>/', CreateCommunication.as_view(), name='create-communication'),
    path('create-communication-job/<int:pk>/', CreateCommunicationJob.as_view(), name='create-communication-job'),
    path('create-communication-venue/<int:pk>/', CreateCommunicationVenue.as_view(), name='create-communication-venue'),
    path('create-course-communication/<int:pk>/<int:course_id>/', CreateCourseCommunication.as_view(), name='create-course-communication'),
    path('create-talent-communication/<int:pk>/', CreateTalentCommunication.as_view(), name='create-talent-communication'),

    path('communication/<int:pk>/', communication_detail, name='communication'),
    path('delete-conversation/<int:pk>/', hide_conversation, name='delete-conversation'),
    # path('delete-conversation/<int:pk>/', HideConversationView.as_view(), name='delete-conversation'),



]

pages/urls.py
from django.urls import path
from .views import *

app_name ='pages'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('talent/', TalentListView.as_view(), name='talent'),
    path('talent/<int:pk>/<slug:slug>', TalentDetailView.as_view(), name='talent-detail'),
    path('profile-info/<int:pk>/<slug:first_name>/', ProfileInfoView.as_view(), name='profile-info'),
    path('search/talent/', searchTalent, name='search-talent'),



]

venues/urls.py
from django.urls import path
from .views import *

app_name = 'venues'

urlpatterns = [
    path('', VenuesView.as_view(), name='venues'),
    path('add-venue/', AddVenueView.as_view(), name='add-venue'),
    path('detail/<int:pk>/', SingleVenueView.as_view(), name='venue-detail'),
    path('update/<int:pk>/', UpdateVenueView.as_view(), name='update-venue'),
    path('delete/<int:pk>/', DeleteVenueView.as_view(), name='delete-venue'),

]

venues/models.py
from django.db import models
from django.conf import settings
from pages.choices import location_choices
from django.template.defaultfilters import slugify

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(default=None, editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def categories_count(self):
        return self.venue_categories.all().count()+500

    def categories_count_listings(self):
        return self.venue_categories.filter(is_published=True).count()+500




class Venue(models.Model):
    name = models.CharField(max_length=250)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='venue_categories')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    address = models.CharField(max_length=350)
    postcode = models.CharField(max_length=10)
    location = models.CharField(max_length=100,
                                blank=False,
                                default=None,
                                choices=location_choices)
    alternate_location = models.CharField(max_length=200, blank=True)
    cost = models.FloatField()
    contact = models.CharField(blank=True, max_length=100)
    contact_mobile = models.CharField(max_length=15, blank=True)
    contact_email = models.CharField(max_length=255, blank=True)
    mirrors = models.BooleanField(default=False)
    wooden_floor = models.BooleanField(default=False)
    music_system = models.BooleanField(default=False)
    floor_type = models.CharField(max_length=255, blank=True)
    notes = models.TextField(blank=True)
    is_published = models.BooleanField(default=True)
    is_allowed = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    venue_image = models.ImageField(upload_to='venue_image/%Y/%m/%d', default='dance_class.jpg')
    venue_image_1 = models.ImageField(upload_to='venue_image/%Y/%m/%d', blank=True)
    venue_image_2 = models.ImageField(upload_to='venue_image/%Y/%m/%d', blank=True)
    slug = models.SlugField(default=None, editable=False)

    def __str__(self):
        return f'{self.id}-{self.name} by {self.author}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.author)
        super(Venue, self).save(*args, **kwargs)

    def updated_info(self):
        if self.updated is None:
            return self.timestamp
        return self.updated


    class Meta:
        ordering = ['-id']

venues/forms.py
from django import forms
from .models import *

class AddVenueForm(forms.ModelForm):
    class Meta:
        model = Venue
        fields = ['name', 'category', 'address', 'postcode','location', 'contact', 'contact_email', 'contact_mobile',
                  'mirrors', 'wooden_floor', 'music_system', 'floor_type', 'cost', 'venue_image', 'venue_image_1', 'venue_image_2']



class UpdateVenueForm(forms.ModelForm):
    class Meta:
        model = Venue
        fields = ['name', 'category', 'address', 'postcode','location', 'contact', 'contact_email', 'contact_mobile',
                  'mirrors', 'wooden_floor', 'music_system', 'floor_type', 'cost', 'venue_image', 'venue_image_1', 'venue_image_2']

venues/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Venue, Category
from pages.choices import location_choices

from .forms import *
# Create your views here.



class VenuesView(ListView):
    template_name = 'venues/venue-listings.html'
    model = Venue
    context_object_name = 'listings'
    paginate_by = 10

    def get_queryset(self):
        queryset = Venue.objects.filter(is_allowed=True)
        return queryset


    def get_context_data(self, *args, **kwargs):
        context = super(VenuesView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['location_choices'] = location_choices
        return context


class SingleVenueView(DetailView):
    template_name = 'venues/single-venue.html'
    model = Venue
    context_object_name = 'venue'

    def get_context_data(self, *args, **kwargs):
        context = super(SingleVenueView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


@method_decorator(login_required(login_url='/'), name='dispatch')
class AddVenueView(SuccessMessageMixin, CreateView):
    model = Venue
    template_name = 'venues/add-venue.html'
    form_class = AddVenueForm
    success_url = '/'
    success_message = 'Your Venue has been successfully listed'

    def form_valid(self, form):
        listing = form.save(commit=False)
        listing.author = self.request.user
        listing.save()
        return super(AddVenueView, self).form_valid(form)

    def get_success_url(self):
        return reverse('venues:venue-detail', kwargs={'pk': self.object.id})


class UpdateVenueView(SuccessMessageMixin, UpdateView):
    model = Venue
    template_name = 'venues/update-venue.html'
    form_class = UpdateVenueForm
    success_message = 'Venue details have successfully been updated !'


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(UpdateVenueView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your message to update !!!')
            return HttpResponseRedirect('/jobs/')
        return super(UpdateVenueView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('venues:venue-detail', kwargs={'pk': self.object.pk})


class DeleteVenueView(SuccessMessageMixin, DeleteView):
    model = Venue
    success_url = '/venues/'
    template_name = 'venues/delete-listing.html'


    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your listing to update !!!')
            return HttpResponseRedirect('/venues/')
        return super(DeleteVenueView, self).get(request, *args, **kwargs)


    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == self.request.user:
            self.object.delete()
            messages.add_message(self.request, messages.SUCCESS, 'Your venue listing has been deleted !!!')
            return HttpResponseRedirect(self.success_url)
        else:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your venue listing to delete !!!')
            return HttpResponseRedirect(self.success_url)

templates/venues/add-venue.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="hero-wrap js-fullheight" style="background-image: url( {% static 'images/ballet_bg_4.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="{% url 'pages:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Add Dance Venue</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Add Venue To Hire</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">



          {% if request.user.is_authenticated %}

			     <form action="#" method="POST" class="p-5 bg-white" ENCTYPE="multipart/form-data">
                 <h2>Add Venue For Hire ...</h2>
                 {% csrf_token %}

                 {% if form.errors %}
                     <div class="alert alert-danger alert-dismissible" role="alert">
                         <div id="form_errors">
                             {% for key,value in form.errors.items %}
                             <span class="fieldWrapper">
                                 {{ key }} : {{ value }}
                             </span>
                             {% endfor %}
                         </div>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="Close">
                             <span aria-hidden="true">&times</span>
                         </button>

                     </div>
                     {% endif %}

                          {{ form | crispy }}





                 <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Create Listing" class="btn btn-primary  py-2 px-5">
                </div>
              </div>




            </form>

          {% else %}

              <h3 class="text-center text-dark">You need to be logged in to create a  listing ps login or register a new account !!</h3>

          {% endif %}
          </div>

          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#"><span class="__cf_email__" data-cfemail="671e081215020a060e0b2703080a060e094904080a">[email&#160;protected]</span></a></p>

            </div>

            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">More Info</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ad iure porro mollitia architecto hic consequuntur. Distinctio nisi perferendis dolore, ipsa consectetur</p>
              <p><a href="#" class="btn btn-primary  py-2 px-4">Learn More</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/venues/delete-listing.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{{ request.user.id }}
    <div class="hero-wrap js-fullheight" style="background-image: url( {% static 'images/ballet_bg_4.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Delete Venue Listing</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Delete Venue Listing</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">
              <h2 class="mb-4">Are you sure you would like to delete this venue listing</h2>
              <h5 class="mb-3">{{ venue.name }}</h5>

              <form action="" method="POST">
                  {% csrf_token %}
                  <a href="{% url 'venues:venue-detail' venue.pk %}" class="btn btn-primary py-2 mr-1">No</a>
                  <button type="submit" class="btn btn-danger">Yes</button>
              </form>
          </div>

          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#"><span class="__cf_email__" data-cfemail="671e081215020a060e0b2703080a060e094904080a">[email&#160;protected]</span></a></p>

            </div>

            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">More Info</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ad iure porro mollitia architecto hic consequuntur. Distinctio nisi perferendis dolore, ipsa consectetur</p>
              <p><a href="#" class="btn btn-primary  py-2 px-4">Learn More</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/venues/single-venue.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/ballet_bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
            {% include 'partials/_alerts.html' %}
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="{% url 'pages:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-3"><a href="{% url 'venues:venues' %}">Venues <i class="ion-ios-arrow-forward"></i></a></span> <span>Detail</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Venue Detail</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">




          <div class="card mb-3 bg-light border-0" style="max-width: 750px;">
                        <div class="row no-gutters">
                            <div class="col-md-4 p-4">
                                <div class="row">
                                    <img src="{{ venue.venue_image.url }}" class="card-img" alt="..." style="max-height: 25rem">
                                </div>
                            <div class="row py-1">
                                    <a href="{% url 'mail:create-communication-venue' venue.pk %}" class="btn btn-outline-info btn-block py-1">
                                        Message Venue
                                    </a>
                            </div>
                                <div class="row">
                                    <div class="tag-widget post-tag-container mb-1 mt-2">
              <div class="tagcloud">
              <div class="amenitiesheading h5">
                  Amenities
              </div>

                  {% if venue.mirrors == True %}
                      <a class="tag-cloud-link btn-block">Mirrors</a>
                  {% endif %}
                  {% if venue.wooden_floor == True%}
                      <a class="tag-cloud-link btn-block">Wooden Floor</a>
                  {% endif %}
                  {% if venue.music_system == True%}
                      <a class="tag-cloud-link btn-block">Music System</a>
                  {% endif %}


              </div>
            </div>
                                </div>


                            </div>
                            <div class="col-md-8">
                                <div class="card-body bg-light">
                                    <h4 class="card-title">{{ venue.name| title }} </h4>
                                    <hr>
                                    <div class="row no-gutters">
                                <div class="container-fluid">
                                    <div class="mt-1 numbers d-flex flex-md-row flex-wrap ">

                                        {% if venue.venue_image_1 %}

                                    <div class="gallery rect-2 mt-0">
                                        <a href="{{ venue.venue_image_1 }}" data-lightbox="mygallery" data-title="">
                                            <img src="{{ venue.venue_image_1.url }}" alt="{{ venue.name }} image-1"/>
                                        </a>
                                    </div>
                                        {% endif %}


                                        {% if venue.venue_image_2 %}
                                            <div class="gallery rect-2 mt-0">
                                                <a href="{{ venue.venue_image_2.url }}" data-lightbox="mygallery" data-title="">
                                                    <img src="{{ venue.venue_image_2.url }}" alt="{{ venue.name }} image-2"/>
                                                </a>
                                            </div>
                                        {% endif %}


                                    </div>
                                </div>
                            </div>



                                    <div class="col-12 text-dark" style="font-size: 1.1em;">Venue Type : {{ venue.category | title }}
                                        <br></div>
                                    <div class="col-12 text-dark mt-2" style="font-size: 1em;">Address</div>
                                    <div class="col-12">{{ venue.address |title }}</div>
                                    <div class="col-12">{{ venue.location }}</div>
                                    <div class="col-12">{{ venue.postcode }}</div>
                                    <div class="col-12 text-dark mt-2" style="font-size: 1em;">Cost: £{{ venue.cost }}ph</div>
                                    <div class="col-12"><p class="card-text"><small class="text-muted">Last
                                        updated {{ venue.updated_info | naturaltime }}</small></p></div>

                                </div>
                            </div>
                        </div>
                    </div>





                    <div class="card mb-3 bg-light border-0" style="max-width: 750px;">
                        <div class="row no-gutters">
                            <div class="col-md-12">
                                <div class="card-body bg-light">
                                    <h5>Notes: </h5>
                                    <div class="col-12"> {{ venue.notes | title }}</div>


                                </div>
                            </div>
                        </div>
                        <div class="row no-gutters">
                            <div class="col-md-9">
                                <div class="card-body bg-light">
                                    <h5 class="card-title">Contact Details</h5>
                                    <hr>

                                    <div class="col-12"> Venue Coordinator : {{ venue.contact | title }}</div>
                                    <div class="col-12">Email: {{ venue.contact_email }}</div>
                                    <div class="col-12">Tel: {{ venue.contact_mobile }}</div>
                                    <div class="col-12"><p class="card-text"><small class="text-muted">Last
                                        updated {{ venue.updated_info | naturaltime }}</small></p></div>

                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="card-body bg-light">



                                </div>
                            </div>
                        </div>
                    </div>
              <hr>













              {% if request.user == venue.author %}

              <div class="tag-widget post-tag-container mb-5 mt-5">
                  <a href="{% url 'venues:delete-venue' venue.pk %}" class="btn btn-danger btn-sm py-1 mr-1">Delete</a>
                  <a href="{% url 'venues:update-venue' venue.pk %}" class="btn btn-primary btn-sm py-1 mr-1">Update</a>
              </div>

              {% endif %}






          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">

            <div class="sidebar-box ftco-animate pt-1">
              <div class="categories">
                <h3 class="text-info pt-0">Categories</h3>
                  {% for category in categories %}
                <li><a href="">{{ category.title }} <span>({{ category.categories_count }})</span></a></li>
                  {% endfor %}

              </div>
            </div>



            <div class="sidebar-box ftco-animate">
              <h3>Advert</h3>
              <div class="tagcloud">

              </div>
            </div>


          </div>

        </div>
      </div>
    </section> <!-- .section -->
{% endblock %}

templates/venues/update-venue.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="hero-wrap js-fullheight" style="background-image: url( {% static 'images/ballet_bg_4.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="{% url 'pages:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Update</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Update Venue Info</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">



          {% if request.user.is_authenticated %}

			     <form action="#" method="POST" class="p-5 bg-white" enctype="multipart/form-data">
                 <h2>Update Venue Listing ...</h2>
                 {% csrf_token %}

                 {% if form.errors %}
                     <div class="alert alert-danger alert-dismissible" role="alert">
                         <div id="form_errors">
                             {% for key,value in form.errors.items %}
                             <span class="fieldWrapper">
                                 {{ key }} : {{ value }}
                             </span>
                             {% endfor %}
                         </div>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="Close">
                             <span aria-hidden="true">&times</span>
                         </button>

                     </div>
                     {% endif %}

                          {{ form | crispy }}





                 <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Update Listing" class="btn btn-primary  py-2 px-5">
                </div>
              </div>




            </form>

          {% else %}

              <h3 class="text-center text-dark">You need to be logged in to create a  listing ps login or register a new account !!</h3>

          {% endif %}
          </div>

          <div class="col-lg-4">


            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Promo</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ad iure porro mollitia architecto hic consequuntur. Distinctio nisi perferendis dolore, ipsa consectetur</p>
              <p><a href="#" class="btn btn-primary  py-2 px-4">Learn More</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}