ballet_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('courses/', include('courses.urls')),
    path('jobs/', include('jobs.urls')),
    path('new-mail/', include('mail.urls')),
    path('venues/', include('venues.urls')),
    path('blogs/', include('blog.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [

    path('', BlogListingsView.as_view(), name='blog-listing'),
    path('detail/<int:pk>/', BlogListingDetail.as_view(), name='blog-detail'),
    path('category-detail/<int:pk>/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('create/', CreateBlogView.as_view(), name='create-blog')

]

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [
    path('listings/', ListingView.as_view(), name='jobs'),
    path('create-listing/', CreateListingView.as_view(), name='create-listing'),
    path('detail/<slug:slug>/<int:pk>/', SingleListingView.as_view(), name='single-listing'),
    path('update-listing/<slug:slug>/<int:pk>/', UpdateListingView.as_view(), name='update-listing'),
    path('delete/listing/<slug:slug>/<int:pk>/', DeleteListingView.as_view(), name='delete-listing'),
    path('delete/posting/<slug:slug>/<int:pk>/', DeletePostingView.as_view(), name='delete-posting'),
    path('category-detail/listings/<slug:slug>/<int:pk>/', CategoryListingsView.as_view(), name='category-listings'),
    path('category-detail/postings/<slug:slug>/<int:pk>/', CategoryPostingsView.as_view(), name='category-postings'),
    path('location-detail/postings/<slug:location>/', LocationPostingsView.as_view(), name='location-postings'),
    path('location-detail/listings/<slug:location>/', LocationListingsView.as_view(), name='location-listings'),
    path('search/listings/', search, name='search-listings'),
    path('search/postings/', searchPosting, name='search-postings'),
    path('postings/', PostingView.as_view(), name='postings'),
    path('create-posting', CreatePostingView.as_view(), name='create-posting'),
    path('post-detail/<slug:slug>/<int:pk>/', SinglePostingView.as_view(), name='single-posting'),
    path('update-posting/<slug:slug>/<int:pk>/', UpdatePostingView.as_view(), name='update-posting'),


]

mail/urls.py
from django.urls import path
from .views import *

app_name = 'mail'

urlpatterns = [
    path('inbox/', inbox, name='inbox'),
    path('inbox-new/', inbox_2, name='inbox'),
    path('outbox/', outbox, name='outbox'),
    path('create-communication/<int:pk>/', CreateCommunication.as_view(), name='create-communication'),
    path('create-communication-job/<int:pk>/', CreateCommunicationJob.as_view(), name='create-communication-job'),
    path('create-communication-venue/<int:pk>/', CreateCommunicationVenue.as_view(), name='create-communication-venue'),
    path('create-course-communication/<int:pk>/<int:course_id>/', CreateCourseCommunication.as_view(), name='create-course-communication'),
    path('create-talent-communication/<int:pk>/', CreateTalentCommunication.as_view(), name='create-talent-communication'),

    path('communication/<int:pk>/', communication_detail, name='communication'),
    path('delete-conversation/<int:pk>/', hide_conversation, name='delete-conversation'),
    # path('delete-conversation/<int:pk>/', HideConversationView.as_view(), name='delete-conversation'),



]

pages/urls.py
from django.urls import path
from .views import *

app_name ='pages'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('talent/', TalentListView.as_view(), name='talent'),
    path('talent/<int:pk>/<slug:slug>', TalentDetailView.as_view(), name='talent-detail'),
    path('profile-info/<int:pk>/<slug:first_name>/', ProfileInfoView.as_view(), name='profile-info'),
    path('search/talent/', searchTalent, name='search-talent'),



]

jobs/forms.py
from django import forms
from .models import *

class CreateListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'description', 'category', 'location', 'rehearsal_date', 'fee', 'listing_image']


class UpdateListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'description', 'category', 'location', 'rehearsal_date', 'fee', 'listing_image']


class CreatePostingForm(forms.ModelForm):

    date = forms.CharField(max_length=20, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type':'date', 'placeholder':'Enter Job Date'}
    ))
    start_time = forms.CharField(max_length=20, widget=forms.TimeInput(
        attrs={'class': 'form-control', 'type': 'time', 'placeholder': 'Enter Job Date'}
    ))
    end_time = forms.CharField(max_length=20, widget=forms.TimeInput(
        attrs={'class': 'form-control', 'type': 'time', 'placeholder': 'Enter Job Date'}
    ))

    class Meta:
        model = Listing
        fields = ['title', 'description',  'date', 'start_time', 'end_time', 'category', 'location', 'rehearsal_date', 'fee', 'listing_image']


class UpdatePostingForm(forms.ModelForm):

    date = forms.CharField(max_length=20, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'Enter Job Date'}
    ))
    start_time = forms.CharField(max_length=20, widget=forms.TimeInput(
        attrs={'class': 'form-control', 'type': 'time', 'placeholder': 'Enter Job Date'}
    ))
    end_time = forms.CharField(max_length=20, widget=forms.TimeInput(
        attrs={'class': 'form-control', 'type': 'time', 'placeholder': 'Enter Job Date'}
    ))
    class Meta:
        model = Listing
        fields = ['title', 'description', 'date', 'start_time', 'end_time', 'category', 'location',
                  'rehearsal_date', 'fee', 'listing_image']

jobs/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin

from mail.models import Conversation, Communication
from .models import Listing, Category
from.forms import *
from pages.choices import location_choices
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponseRedirect
from users.models import  Account


# Create your views here.

class ListingView(ListView):
    template_name = 'jobs/listings.html'
    model = Listing
    context_object_name = 'listings'
    paginate_by = 10

    def get_queryset(self):
        queryset = Listing.objects.filter(is_posting=True)
        return queryset


    def get_context_data(self, *args, **kwargs):
        context = super(ListingView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['location_choices'] = location_choices
        return context





@method_decorator(login_required(login_url='/'), name='dispatch')
class CreateListingView(SuccessMessageMixin, CreateView):
    model = Listing
    template_name = 'jobs/create-listing.html'
    form_class = CreateListingForm
    success_url = '/'
    success_message = 'Your job has been successfully created'
    
    
    def form_valid(self, form):
        listing = form.save(commit=False)
        listing.author = self.request.user
        listing.save()
        return super(CreateListingView, self).form_valid(form)

    def get_success_url(self):
        return reverse('jobs:single-listing',  kwargs={'slug': self.object.slug, 'pk': self.object.id})


class SingleListingView(DetailView):
    template_name = 'jobs/single-listing.html'
    model = Listing
    context_object_name = 'listing'

    def get_context_data(self, *args, **kwargs):
        context = super(SingleListingView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context



    def post(self, *args, **kwargs):
        user = self.request.user

        if self.request.method == 'POST':
            title = self.request.POST['title']
            sender = user
            recipient = self.request.POST['recipient']
            content = self.request.POST['content']

            recipient = Account.objects.get(id=recipient)

            print(content)

            conversation = Conversation.objects.create(title=title, messenger_1=sender, messenger_2=recipient)

            conversation_id = conversation.id

            communication = Communication(content=content,
                                          sender=sender,
                                          recipient=recipient,
                                          conversation_id=conversation_id
                                          )
            communication.save()
            return redirect('/')

class CategoryListingsView(ListView):
    model = Listing
    template_name = 'jobs/category-detail.html'
    context_object_name = 'listings'
    paginate_by = 10

    def get_queryset(self):
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return Listing.objects.filter(category=self.category).filter(is_posting=True)



    def get_context_data(self, *args, **kwargs):
        context = super(CategoryListingsView, self).get_context_data(*args, **kwargs)
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        context['categories'] = Category.objects.all()
        context['category'] = self.category
        return context



def search(request):

    queryset_list = Listing.objects.all().filter(is_posting=True)


    if 'job_title' in request.GET:
        job_title = request.GET['job_title']
        if job_title:
            queryset_list = queryset_list.filter(title__icontains=job_title)

    if 'job_type' in request.GET:
        job_type = request.GET['job_type']
        if job_type:
            queryset_list = queryset_list.filter(category=job_type)

    if 'job_location' in request.GET:
        location = request.GET['job_location']
        if location:
            queryset_list = queryset_list.filter(location=location)

    paginator = Paginator(queryset_list, 2)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)


    context = {
        'listings': paged_listings,
        'categories':Category.objects.all().order_by('title'),
        'location_choices':location_choices,
        'values': request.GET

    }

    return render(request, 'jobs/search.html', context)


def searchPosting(request):

    queryset_list = Listing.objects.filter(is_posting=False)


    if 'job_title' in request.GET:
        job_title = request.GET['job_title']
        if job_title:
            queryset_list = queryset_list.filter(title__icontains=job_title)

    if 'job_type' in request.GET:
        job_type = request.GET['job_type']
        if job_type:
            queryset_list = queryset_list.filter(category=job_type)

    if 'job_location' in request.GET:
        location = request.GET['job_location']
        if location:
            queryset_list = queryset_list.filter(location=location)

    paginator = Paginator(queryset_list, 2)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)


    context = {
        'listings': paged_listings,
        'categories':Category.objects.all().order_by('title'),
        'location_choices':location_choices,
        'values': request.GET

    }

    return render(request, 'jobs/search-postings.html', context)


class UpdateListingView(SuccessMessageMixin, UpdateView):
    model = Listing
    template_name = 'jobs/update-listing.html'
    form_class = UpdateListingForm
    success_message = ' : You have successfully updated your job Listing !'


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(UpdateListingView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your message to update !!!')
            return HttpResponseRedirect('/jobs/')
        return super(UpdateListingView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('jobs:single-listing', kwargs={'pk': self.object.pk, 'slug': self.object.slug})


class DeleteListingView(SuccessMessageMixin, DeleteView):
    model = Listing
    template_name = 'jobs/delete-listing.html'


    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your message to update !!!')
            return HttpResponseRedirect('/jobs/')
        return super(DeleteListingView, self).get(request, *args, **kwargs)


    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == self.request.user:
            self.object.delete()
            messages.add_message(self.request, messages.SUCCESS, 'Your job listing has been deleted !!!')
            return HttpResponseRedirect(reverse('users:profile', kwargs={'pk': self.request.user.id}))
        else:
            messages.add_message(self.request, messages.WARNING, ': This Message has not been deleted!')
            return HttpResponseRedirect( reverse('jobs:single-listing', kwargs={'pk': self.object.pk, 'slug': self.object.slug}))




class PostingView(ListView):
    template_name = 'jobs/postings.html'
    model = Listing
    context_object_name = 'listings'
    paginate_by = 10

    def get_queryset(self):
        queryset = Listing.objects.filter(is_posting=False).order_by('date')
        return queryset


    def get_context_data(self, *args, **kwargs):
        context = super(PostingView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['location_choices'] = location_choices
        return context


@method_decorator(login_required(login_url='/'), name='dispatch')
class CreatePostingView(SuccessMessageMixin, CreateView):
    model = Listing
    template_name = 'jobs/create-posting.html'
    form_class = CreatePostingForm
    success_message = 'Your job has been succesfully created'

    def form_valid(self, form):
        listing = form.save(commit=False)
        listing.author = self.request.user
        listing.is_posting = False
        listing.save()
        return super(CreatePostingView, self).form_valid(form)

    def get_success_url(self):
        return reverse('jobs:single-posting', kwargs={'slug': self.object.slug, 'pk': self.object.id})


class UpdatePostingView(SuccessMessageMixin, UpdateView):
    model = Listing
    template_name = 'jobs/update-posting.html'
    form_class = UpdatePostingForm
    success_message = ': You have successfully updated your job !'


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(UpdatePostingView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your message to update !!!')
            return HttpResponseRedirect('/jobs/')
        return super(UpdatePostingView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('jobs:single-listing', kwargs={'pk': self.object.pk, 'slug': self.object.slug})

templates/jobs/delete-listing.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="hero-wrap js-fullheight" style="background-image: url( {% static 'images/ballet_bg_4.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="{% url 'pages:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Delete Job</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Delete Job</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">
              <h2 class="mb-4">Are you sure you would like to delete this Jobs ? <br> <span class="h5">{{ object.title }}</span></h2>


              <form action="" method="POST">
                  {% csrf_token %}
                  <a href="{% url 'jobs:single-listing' listing.slug listing.pk %}" class="btn btn-primary py-2 mr-1">No</a>
                  <button type="submit" class="btn btn-danger">Yes</button>
              </form>
          </div>

          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#"><span class="__cf_email__" data-cfemail="671e081215020a060e0b2703080a060e094904080a">[email&#160;protected]</span></a></p>

            </div>

            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">More Info</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ad iure porro mollitia architecto hic consequuntur. Distinctio nisi perferendis dolore, ipsa consectetur</p>
              <p><a href="#" class="btn btn-primary  py-2 px-4">Learn More</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/jobs/single-listing.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/ballet_bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
            {% include 'partials/_alerts.html' %}
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="{% url 'pages:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-3"><a href="{% url 'jobs:jobs' %}">Listings <i class="ion-ios-arrow-forward"></i></a></span> <span>Single</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Job Detail</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">

                    <div class="card mb-3 bg-light border-0" style="max-width: 750px;">
                        <div class="row no-gutters">

                            <div class="col-md-12">
                                <div class="card-body bg-light">
                                    <h3 class="card-title">{{ listing.title | title }}</h3>
                                    <hr>
                                    <div class="row p-2 bg-white"
                                         style=" border-bottom: solid; border-bottom-width:1px; border-bottom-color: green;">
                                        <div class="col-md-6 ">
                                        Category: {{ listing.category }}
                                    </div>
                                    <div class="col-md-6 job-split">
                                        Location: {{ listing.location }}<br>
                                        Fee: £{{ listing.fee }}<br>

                                    </div>

                                    </div>

                                    <div class="col-12 text-dark"><h5 class="mt-3">Description :</h5></div>





                                    <div class="col-12 mt-3">{{ listing.description.title | linebreaks }}</div>

                                    <div class="row p-2 bg-white">
                                        <div class="col-12"><p class="card-text"><small class="text-muted">Posted {{ listing.publish_date | naturaltime }}
                                        <br>  by <a href="{% url 'pages:profile-info' listing.author.id listing.author.first_name %}">{{ listing.author.first_name }}</a></small></p></div>
                                    </div>



                                </div>
                            </div>
                        </div>
                    </div>

          {% if request.user != listing.author %}
      <div class="row">
                           <div class="col-12 mt-2">
                               <a href="{% url 'mail:create-communication-job'  listing.pk %}" class="float-right btn btn-outline-info btn-sm">Make Enquiry</a>
                           </div>

                       </div>
          {% endif %}






              <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                <a href="{% url 'jobs:location-listings' listing.location %}" class="tag-cloud-link">{{ listing.location }}</a>
                <a href="{% url 'jobs:category-listings' listing.category.slug listing.category.pk %}" class="tag-cloud-link">{{ listing.category }}</a>

              </div>
            </div>
              <hr>




              {% if request.user == listing.author %}

              <div class="tag-widget post-tag-container mb-5 mt-5">
                  <a href="{% url 'jobs:delete-listing' listing.slug listing.pk %}" class="btn btn-danger btn-sm py-1 mr-1">Delete</a>
                  <a href="{% url 'jobs:update-listing' listing.slug listing.pk %}" class="btn btn-primary btn-sm py-1 mr-1">Update</a>
              </div>

              {% endif %}







          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3 class="text-info">Job Categories</h3>
                  {% for category in categories %}
                <li><a href="{% url 'jobs:category-listings' category.slug category.pk %}">{{ category.title }} <span>({{ category.categories_count_listings }})</span></a></li>
                  {% endfor %}
              </div>
            </div>

          <div class="sidebar-box ftco-animate">
              <div class="categories">
              <h3>Specific Date Job Categories</h3>
                  {% for category in categories %}
                <li><a href="{% url 'jobs:category-postings' category.slug category.pk %}">{{ category.title }} <span>({{ category.categories_count_postings }})</span></a></li>
                  {% endfor %}

              </div>
            </div>



        </div>
      </div>


    <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="" method="POST">
              {% csrf_token %}
            <div class="form-group">
              <label for="property_name" class="col-form-label">Title</label>
              <input type="text" name="title" class="form-control" value="{{ listing.title }}" >
            </div>

            <div class="form-group">
              <label for="name" class="col-form-label">Sender:</label>
              <input type="text" name="name" class="form-control" value="{{ request.user }}" >
            </div>
            <div class="form-group">
              <label for="name" class="col-form-label">Recipient:</label>
              <input type="text" name="recipient" class="form-control" value="{{ listing.author.id }}" >
            </div>

            <div class="form-group">
              <label for="message" class="col-form-label">Message:</label>
              <textarea name="content" class="form-control"></textarea>
            </div>
            <hr>
            <input type="submit" value="Send" class="btn btn-block btn-secondary">
          </form>
        </div>
      </div>
    </div>
  </div>
    </section> <!-- .section -->
{% endblock %}

templates/jobs/single-posting.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/ballet_bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
            {% include 'partials/_alerts.html' %}
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="{% url 'pages:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-3"><a href="{% url 'jobs:postings' %}">Specific Date Job <i class="ion-ios-arrow-forward"></i></a></span> <span>Single</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Specific Date Job</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">

           <div class="card mb-3 bg-light border-0" style="max-width: 750px;">
                        <div class="row no-gutters">

                            <div class="col-md-12">
                                <div class="card-body bg-light">
                                    <h3 class="card-title">{{ listing.title | title }}</h3>
                                    <hr>
                                    <div class="row p-2 bg-white"
                                         style=" border-bottom: solid; border-bottom-width:1px; border-bottom-color: steelblue;">
                                        <div class="col-md-6 ">
                                            Job Date: {{ listing.date  }} <br>
                                            Job Time: {{ listing.start_time  }} - {{ listing.end_time }} <br>
                                        Category: {{ listing.category }}
                                    </div>
                                    <div class="col-md-6 posting-split">
                                        Location: {{ listing.location }}<br>
                                        Fee: £{{ listing.fee }}<br>

                                    </div>

                                    </div>

                                    <div class="col-12 text-dark"><h5 class="mt-3">Description :</h5></div>





                                    <div class="col-12 mt-3">{{ listing.description.title | linebreaks }}</div>

                                    <div class="row p-2 bg-white">
                                        <div class="col-12"><p class="card-text"><small class="text-muted">Posted {{ listing.publish_date | naturaltime }}
                                        <br>  by <a href="{% url 'pages:profile-info' listing.author.id listing.author.first_name %}">{{ listing.author.first_name }}</a></small></p></div>
                                    </div>



                                </div>
                            </div>
                        </div>
                    </div>














 {% if request.user != listing.author %}
      <div class="row">
                           <div class="col-12 mt-2">
                               <a href="{% url 'mail:create-communication-job'  listing.pk %}" class="float-right btn btn-outline-info btn-sm">Make Enquiry</a>
                           </div>

                       </div>
          {% endif %}


           <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                <a href="{% url 'jobs:location-postings' listing.location %}" class="tag-cloud-link">{{ listing.location }}</a>
                <a href="{% url 'jobs:category-postings' listing.category.slug listing.category.pk %}" class="tag-cloud-link">{{ listing.category }}</a>

              </div>
            </div>
              <hr>




              {% if request.user == listing.author %}

              <div class="tag-widget post-tag-container mb-5 mt-5">
                  <a href="{% url 'jobs:delete-posting' listing.slug listing.pk %}" class="btn btn-danger btn-sm py-1 mr-1">Delete</a>
                  <a href="{% url 'jobs:update-posting' listing.slug listing.pk %}" class="btn btn-primary btn-sm py-1 mr-1">Update</a>
              </div>

              {% endif %}









          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">

           <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3 class="text-info">Job Categories</h3>
                  {% for category in categories %}
                <li><a href="{% url 'jobs:category-listings' category.slug category.pk %}">{{ category.title }} <span>({{ category.categories_count_listings }})</span></a></li>
                  {% endfor %}
              </div>
            </div>

          <div class="sidebar-box ftco-animate">
              <div class="categories">
              <h3 class="text-info">Specific Date Job Categories</h3>
                  {% for category in categories %}
                <li><a href="{% url 'jobs:category-postings' category.slug category.pk %}">{{ category.title }} <span>({{ category.categories_count_postings }})</span></a></li>
                  {% endfor %}

              </div>
            </div>






          </div>

        </div>
      </div>
    </section> <!-- .section -->
{% endblock %}