ballet_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('courses/', include('courses.urls')),
    path('jobs/', include('jobs.urls')),
    path('new-mail/', include('mail.urls')),
    path('venues/', include('venues.urls')),
    path('blogs/', include('blog.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [

    path('', BlogListingsView.as_view(), name='blog-listing'),
    path('detail/<int:pk>/', BlogListingDetail.as_view(), name='blog-detail'),
    path('category-detail/<int:pk>/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('create/', CreateBlogView.as_view(), name='create-blog')

]

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [

    path('', CoursesView.as_view(), name='courses'),
    path('create/', CreateCourseView.as_view(), name='create-course'),
    path('level/<int:pk>/<slug:slug>/', CourseLevelDetailView.as_view(), name='level_detail'),
    path('detail/<int:pk>/<slug:slug>/', SingleCourseView.as_view(), name='course-detail'),
    path('update/<int:pk>/<slug:slug>/', UpdateCourseView.as_view(), name='update-course'),
    path('delete/<int:pk>/<slug:slug>/', DeleteCourseView.as_view(), name='delete-course'),
    path('search/', searchCourse, name='search-course'),
    path('create-review/<int:pk>/', CreateCourseReview.as_view(), name='create-review'),
    path('update-review/<int:pk>/', UpdateCourseReview.as_view(), name='update-review'),
    path('delete-review/<int:pk>/', DeleteReviewView.as_view(), name='delete-review'),

]

mail/urls.py
from django.urls import path
from .views import *

app_name = 'mail'

urlpatterns = [
    path('inbox/', inbox, name='inbox'),
    path('inbox-new/', inbox_2, name='inbox'),
    path('outbox/', outbox, name='outbox'),
    path('create-communication/<int:pk>/', CreateCommunication.as_view(), name='create-communication'),
    path('create-communication-job/<int:pk>/', CreateCommunicationJob.as_view(), name='create-communication-job'),
    path('create-communication-venue/<int:pk>/', CreateCommunicationVenue.as_view(), name='create-communication-venue'),
    path('create-course-communication/<int:pk>/<int:course_id>/', CreateCourseCommunication.as_view(), name='create-course-communication'),
    path('create-talent-communication/<int:pk>/', CreateTalentCommunication.as_view(), name='create-talent-communication'),

    path('communication/<int:pk>/', communication_detail, name='communication'),
    path('delete-conversation/<int:pk>/', hide_conversation, name='delete-conversation'),
    # path('delete-conversation/<int:pk>/', HideConversationView.as_view(), name='delete-conversation'),



]

pages/urls.py
from django.urls import path
from .views import *

app_name ='pages'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('talent/', TalentListView.as_view(), name='talent'),
    path('talent/<int:pk>/<slug:slug>', TalentDetailView.as_view(), name='talent-detail'),
    path('profile-info/<int:pk>/<slug:first_name>/', ProfileInfoView.as_view(), name='profile-info'),
    path('search/talent/', searchTalent, name='search-talent'),



]

courses/forms.py
from django import forms
from .models import *

class CreateCoursesForm(forms.ModelForm):
    class Meta:
        model = WeeklyBalletClass
        fields = ['title', 'location', 'course_level', 'age_group', 'day', 'start_time', 'end_time', 'address',
                  'postcode', 'price', 'teacher', 'faq', 'clothes', 'experience', 'average_age', 'drop_in',
                  'about_dance_class', 'dance_class_image', 'dance_class_image_1', 'dance_class_image_2', 'dance_class_image_3']







class UpdateCourseForm(forms.ModelForm):
    class Meta:
        model = WeeklyBalletClass
        fields = ['title', 'location', 'course_level', 'age_group', 'day', 'start_time', 'end_time', 'address',
                  'postcode', 'price', 'teacher', 'faq', 'clothes', 'experience', 'average_age', 'drop_in',
                  'about_dance_class', 'dance_class_image', 'dance_class_image_1', 'dance_class_image_2', 'dance_class_image_3']




class CourseReviewForm(forms.ModelForm):
    class Meta:
        model = CourseReview
        fields = ['comment', 'rating']

        labels = {
            'comment': ('Review'),
            'rating': ('Rating out of 10'),
        }

        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'label': 'review'}),
            'rating': forms.TextInput(attrs={ 'type':'range', 'id' :'rangeInput',
                                             'min':'0', 'max':'10', 'step':'0.5', 'oninput': 'amount.value=rangeInput.value',
                                             }),

        }

courses/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import WeeklyBalletClass, Level, CourseReview
from .forms import CreateCoursesForm, UpdateCourseForm, CourseReviewForm
from pages.choices import location_choices, course_level_choices, age_choices, day_choices
from django.db.models import Avg












class CoursesView(ListView):
    model = WeeklyBalletClass
    template_name = 'courses/course-list.html'
    paginate_by = 10
    context_object_name = 'courses'

    def get_context_data(self, **kwargs):
        context = super(CoursesView, self).get_context_data(**kwargs)
        context['levels'] = Level.objects.all()
        context['age_choices'] = age_choices
        context['location_choices'] = location_choices
        return context

class SingleCourseView(DetailView):
    template_name = 'courses/single-course.html'
    model = WeeklyBalletClass
    context_object_name = 'course'





    def get_context_data(self, *args, **kwargs):
        context = super(SingleCourseView, self).get_context_data(**kwargs)
        context['levels'] = Level.objects.all()
        ratings = CourseReview.objects.filter(course_id=self.kwargs['pk'])
        average = ratings.aggregate(Avg('rating'))['rating__avg']
        if average is not None:
            context['average'] = (round(average, 1))
        context['ratings'] = CourseReview.objects.filter(course_id=self.kwargs['pk'])
        commenters= CourseReview.objects.filter(course_id=self.kwargs['pk'])

        users=[]
        for commenter in commenters:
            users.append(commenter.user)
        context['commenters'] = users

        return context


@method_decorator(login_required(login_url='/'), name='dispatch')
class CreateCourseView(SuccessMessageMixin, CreateView):
    model = WeeklyBalletClass
    template_name = 'courses/create-course.html'
    form_class = CreateCoursesForm
    success_url = '/'
    success_message = 'Your job has been succesfully created'

    def form_valid(self, form):
        courses = form.save(commit=False)
        courses.author = self.request.user
        courses.save()
        return super(CreateCourseView, self).form_valid(form)

    def get_success_url(self):
        return reverse('courses:course-detail', kwargs={'pk': self.object.id, 'slug': self.object.slug})


@method_decorator(login_required(login_url='/'), name='dispatch')
class UpdateCourseView(SuccessMessageMixin, UpdateView):
    model = WeeklyBalletClass
    template_name = 'courses/update-course.html'
    form_class = UpdateCourseForm
    success_message = 'You have successfully updated your job !'


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(UpdateCourseView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your message to update !!!')
            return HttpResponseRedirect('/jobs/')
        return super(UpdateCourseView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('courses:course-detail', kwargs={'pk': self.object.pk, 'slug': self.object.slug})


@method_decorator(login_required(login_url='/'), name='dispatch')
class DeleteCourseView(SuccessMessageMixin, DeleteView):
    model = WeeklyBalletClass
    context_object_name = 'course'
    template_name = 'courses/delete-course.html'


    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your dance class to delete !!!')
            return HttpResponseRedirect(reverse('courses:course-detail', kwargs={'pk': self.object.pk, 'slug': self.object.slug}))
        return super(DeleteCourseView, self).get(request, *args, **kwargs)


    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == self.request.user:
            self.object.delete()
            messages.add_message(self.request, messages.SUCCESS, 'Your course  has been deleted !!!')
            return HttpResponseRedirect('/courses/')
        else:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your review  to delete !!!')
            return HttpResponseRedirect('/courses/')




class CourseLevelDetailView(ListView):
    model = WeeklyBalletClass
    template_name = 'courses/level-detail.html'
    context_object_name = 'courses'
    paginate_by = 2

    def get_queryset(self):
        self.level = get_object_or_404(Level, pk=self.kwargs['pk'])
        return WeeklyBalletClass.objects.filter(course_level=self.level).filter(is_allowed=True)


    def get_context_data(self, *args, **kwargs):
        context = super(CourseLevelDetailView, self).get_context_data(*args, **kwargs)
        self.level = get_object_or_404(Level, pk=self.kwargs['pk'])
        context['levels'] = Level.objects.all()
        context['level'] = self.level
        context['age_choices'] = age_choices
        context['location_choices'] = location_choices
        return context


def searchCourse(request):

    queryset_list = WeeklyBalletClass.objects.all()


    if 'age_group' in request.GET:
        age = request.GET['age_group']
        if age:
            queryset_list = queryset_list.filter(age_group=age)

    if 'course_level' in request.GET:
        level = request.GET['course_level']
        if level:
            queryset_list = queryset_list.filter(course_level=level)

    if 'course_location' in request.GET:
        location = request.GET['course_location']
        if location:
            queryset_list = queryset_list.filter(location=location)

    paginator = Paginator(queryset_list, 10)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)


    context = {
        'courses': paged_listings,
        'levels':Level.objects.all().order_by('title'),
        'location_choices':location_choices,
        'age_choices': age_choices,
        'values': request.GET

    }

    return render(request, 'courses/search.html', context)



@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class CreateCourseReview(CreateView):
    model = CourseReview
    template_name = 'courses/create-course_review.html'
    form_class = CourseReviewForm

    def get(self, request, *args, **kwargs):
        self.course = get_object_or_404(WeeklyBalletClass, pk=self.kwargs['pk'])



        if request.user == self.course.author:
            messages.add_message(self.request, messages.WARNING, 'You cant give your self a  review')
            return HttpResponseRedirect(reverse('courses:course-detail', kwargs={'pk': self.course.pk, 'slug': self.course.slug}))

        commenters = CourseReview.objects.filter(course_id=self.kwargs['pk'])
        for commenter in commenters:
            users = [commenter.user]
            if request.user in users:
                messages.add_message(self.request, messages.WARNING, 'Cheeky you have allready reviewed this class')
                return HttpResponseRedirect('/courses/')
        return super(CreateCourseReview, self).get(request, *args, **kwargs)



    def form_valid(self, form):
        course = get_object_or_404(WeeklyBalletClass, pk=self.kwargs['pk'])
        form = form.save(commit=False)
        form.user = self.request.user
        form.course = course
        form.save()
        messages.add_message(self.request, messages.SUCCESS, 'Your Review has been posted')
        return super(CreateCourseReview, self).form_valid(form)


    def get_context_data(self, *args, **kwargs):
        context = super(CreateCourseReview, self).get_context_data(*args, **kwargs)
        self.course = get_object_or_404(WeeklyBalletClass, pk=self.kwargs['pk'])
        context['course'] = self.course
        return context


    def get_success_url(self):
        self.course = get_object_or_404(WeeklyBalletClass, pk=self.kwargs['pk'])
        return reverse('courses:course-detail', kwargs={'pk': self.course.pk, 'slug': self.course.slug})


@method_decorator(login_required(login_url='/'), name='dispatch')
class UpdateCourseReview(UpdateView):
    model = CourseReview
    template_name = 'courses/create-course_review.html'
    form_class = CourseReviewForm

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(CourseReview, pk=self.kwargs['pk'])
        if self.object.user != request.user:
            messages.add_message(self.request, messages.WARNING, 'Cheeky not your Review to update !!!')
            return HttpResponseRedirect('/courses/')
        return super(UpdateCourseReview, self).get(request, *args, **kwargs)




    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, 'Your Review has been updated')
        return super(UpdateCourseReview, self).form_valid(form)




    def get_success_url(self):
        dance_course = get_object_or_404(WeeklyBalletClass, pk=self.object.course.id)
        return reverse('courses:course-detail', kwargs={'pk': dance_course.pk, 'slug': dance_course.slug})




@method_decorator(login_required(login_url='/'), name='dispatch')
class DeleteReviewView(SuccessMessageMixin, DeleteView):
    model = CourseReview
    context_object_name = 'review'
    template_name = 'courses/delete-course-review.html'


    def get(self, request, *args, **kwargs):

templates/courses/delete-course-review.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{{ request.user.id }}
    <div class="hero-wrap js-fullheight" style="background-image: url( {% static 'images/ballet_bg_4.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Register An Account</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Delete Review</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">
              <h2 class="mb-4">Are you sure you would like to delete this Review</h2>
              <p>{{ review.comment }}</p>

              <form action="" method="POST">
                  {% csrf_token %}
                  <a href="{% url 'courses:course-detail' review.course.pk review.course.slug%}" class="btn btn-primary py-2 mr-1">No</a>
                  <button type="submit" class="btn btn-danger">Yes</button>
              </form>
          </div>

          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#"><span class="__cf_email__" data-cfemail="671e081215020a060e0b2703080a060e094904080a">[email&#160;protected]</span></a></p>

            </div>

            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">More Info</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa ad iure porro mollitia architecto hic consequuntur. Distinctio nisi perferendis dolore, ipsa consectetur</p>
              <p><a href="#" class="btn btn-primary  py-2 px-4">Learn More</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/courses/single-course.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/ballet_bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
            {% include 'partials/_alerts.html' %}
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="{% url 'pages:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-3"><a href="{% url 'courses:courses' %}">Ballet Classes <i class="ion-ios-arrow-forward"></i></a></span> <span>Detail</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Class Detail</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">


           <div class="card mb-3 bg-light border-0" style="max-width: 750px;">
                        <div class="row no-gutters">
                            <div class="col-md-4 p-4">
                                <div class="row">
                                    <img src="{{ course.dance_class_image.url }}" class="card-img" alt="..." style="max-height: 25rem">
                                </div>
                                {% if course.author != request.user %}
                                <div class="row pt-1">
                                    <a href="{% url 'mail:create-course-communication'  course.author.pk course.pk %}"
                                       class=" btn btn-outline-info btn-sm btn-block">MESSAGE {{ course.author.first_name | upper }}</a>

                                </div>
                                {% endif %}


                            </div>
                            <div class="col-md-8">
                                <div class="card-body bg-light">
                                <h4 class="card-title">{{ course.title| title }} </h4>
                                <div class="row">
                                    <div class="col-8">
                                        Class Rating
                                    </div>
                                    <div class="col-4">
                                        <h5 class="text-right text-info">
                                            {% if average %}
                                            {{ average }}/10 </h5>
                                        {% else %}
                                        Not Rated
                                        {% endif %}
                                    </div>
                                </div>

                                    <hr>
                                    <div class="row no-gutters">
                                <div class="container-fluid">
                                    <div class="mt-1 numbers d-flex flex-md-row flex-wrap ">

                                        {% if course.dance_class_image_1 %}

                                    <div class="gallery rect-2 mt-0">
                                        <a href="{{ course.dance_class_image_1.url }}" data-lightbox="mygallery" data-title="">
                                            <img src="{{ course.dance_class_image_1.url }}" alt="{{ course.title }} image-1"/>
                                        </a>
                                    </div>
                                        {% endif %}


                                        {% if course.dance_class_image_2 %}
                                            <div class="gallery rect-2 mt-0">
                                                <a href="{{ course.dance_class_image_2.url }}" data-lightbox="mygallery" data-title="">
                                                    <img src="{{ course.dance_class_image_2.url }}" alt="{{ course.title }} image-2"/>
                                                </a>
                                            </div>
                                        {% endif %}


                                    </div>
                                </div>
                            </div>



                                    <div class="col-12">{{ course.age_group | title }} {{ course.course_level | title }}</div>
                                    <div class="col-12">{{ course.day | title }} {{ course.start_time }}-{{ course.end_time }}</div>
                                    <div class="col-12">{{ course.location | title }}</div>
                                    <div class="col-12"><p class="card-text"><small class="text-muted">Last
                                        updated {{ course.updated_info | naturaltime }}</small></p></div>

                                </div>
                            </div>
                        </div>
                    </div>


{#          <div class="card mb-3 bg-light border-0" style="max-width: 750px;">#}
{#                        <div class="row no-gutters">#}
{##}
{#                            <div class="col-md-12">#}
{#                                <div class="card-body bg-light">#}
{##}
{#                                    <div class="row">#}
{#                                        <div class="col-6">#}
{#                                            <a href="{% url 'courses:create-review' course.pk  %}" class="btn btn-outline-info btn-block float-left py-0">Create Review</a>#}
{#                                        </div>#}
{#                                        <div class="col-6">#}
{#                                            <h5>9.5/10</h5>#}
{#                                        </div>#}
{#                                    </div>#}
{##}
{##}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}


          <div class="card mb-3 bg-light border-0" style="max-width: 750px;">
                        <div class="row no-gutters">

                            <div class="col-md-12">
                                <div class="card-body bg-light">
                                    <h4 class="card-title">{{ course.age_group | title}} {{ course.course_level }} Ballet Dance Class in {{ course.location | title }}</h4>
                                    <hr>




                                    <div class="col-12">{{ course.day | title }} {{ course.start_time }}-{{ course.end_time }}</div>
                                    <div class="col-12 text-dark"><br>Address :</div>
                                    <div class="col-12">{{ course.address | title }}</div>
                                    <div class="col-12">{{ course.location | title }}</div>
                                    <div class="col-12">{{ course.postcode | title }}</div>
                                    <div class="col-12"><p class="text-dark"> Cost: £{{ course.price|floatformat }} </p></div>
                                    <div class="col-12"><p class="card-text"><small class="text-muted">Last
                                        updated {{ course.updated_info | naturaltime }}</small></p></div>

                                </div>
                            </div>
                        </div>
                    </div>


           <div class="card mb-3 bg-light border-0" style="max-width: 750px;">
                        <div class="row no-gutters">

                            <div class="col-md-12">
                                <div class="card-body bg-light">
                                    <h4 class="card-title">More Info</h4>
                                    <hr>
                                    <p><span class="text-dark">About The Class :</span>
                                      {{ course.about_dance_class | linebreaks }}</p>
                                  <p><span class="text-dark">faq :</span>
                                      {{ course.faq | linebreaks }}</p>
                                  <p><span class="text-dark">Experience:</span>
                                      {{ course.experience | linebreaks }}</p>
                                  <p><span class="text-dark">Clothes:</span>
                                      {{ course.clothes | linebreaks }}</p>
                                  <p><span class="text-dark">Average Age :</span>
                                      {{ course.average_age | linebreaks }}</p>
                                  <p><span class="text-dark">Is this a  Drop in class or Course:</span>
                                      {{ course.drop_in | linebreaks }}</p>

                                </div>
                            </div>
                        </div>
                    </div>






              {% if request.user == course.author %}

              <div class="tag-widget post-tag-container mb-5 mt-5">
                  <a href="{% url 'courses:delete-course' course.pk course.slug %}" class="btn btn-danger btn-sm py-1 mr-1">Delete</a>
                  <a href="{% url 'courses:update-course' course.pk course.slug %}" class="btn btn-primary btn-sm py-1 mr-1">Update</a>
              </div>

              {% endif %}




            <div class="card mb-3 bg-light border-0" style="max-width: 750px;">
                        <div class="row no-gutters">

                            <div class="col-md-12">
                                <div class="card-body bg-light">
                                <div class="row">
                                    <div class="col-6">
                                        <h4 class="card-title">Reviews</h4>
                                    </div>
                                {% if request.user != course.author %}
                                    {% if request.user not in commenters %}
                                        <div class="col-6">
                                            <a href="{% url 'courses:create-review' course.pk  %}" class="btn btn-outline-info float-right py-0">Write Review</a>
                                        </div>

                                    {% else %}
                                        <div class="col-6">
                                        <p class="text-sm float-right">You have written a  review</p>
                                        </div>
                                    {% endif %}
                                {% endif %}
                                </div>






                                    {%  for rating in ratings %}


                                    <div class="card mb-2">
                                      <div class="card-body py-1">
                                        <div class="row">
                                            <div class="col-md-3">
                                                <p class="text-left">{{ rating.user.first_name | title }}</p>
                                                <h5 class="pb-0 mb-0">{{ rating.rating }}</h5>

                                            </div>
                                            <div class="col-md-9">
                                                <p>{{ rating.comment }}</p>
                                            </div>

                                        </div>
                                          {% if request.user == rating.user %}
                                          <div class="row">

                                                    <div class="col-12">
                                                        <a href="{% url 'courses:delete-review' rating.pk  %}" class=" btn btn-outline-danger btn-sm py-0 float-right">Delete Review</a>
                                                        <a href="{% url 'courses:update-review' rating.pk  %}" class=" btn btn-outline-info btn-sm py-0 mr-2 float-right">Update Review</a>

                                                    </div>

                                                </div>
                                          {% endif %}
                                      </div>
                                    </div>

                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>







          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">

            <div class="sidebar-box ftco-animate pt-1">
              <div class="categories">
                <h3>Categories</h3>
                  {% for level in levels %}
                <li><a href="{% url 'courses:level_detail' level.pk level.title %}">{{ level.title }} <span>({{ level.courses_count }})</span></a></li>
                  {% endfor %}

              </div>
            </div>



            <div class="sidebar-box ftco-animate">
              <h3>Promo</h3>

            </div>


          </div>

        </div>
      </div>
    </section> <!-- .section -->
{% endblock %}